BBVAFSW3T3-23
alkemyTech/BBVA-FS-W3-Back-T3 pull request #12
Opened 2023-07-05 20:31 UTC by Damian-Pereyra-dv

Endpoint de registro de usuarios/ V2

2023-07-07 12:57 UTC, MaiCaiIney requested changes
Por favor subir la collection de Postman para probar el endpoint nuevo.

2023-07-07 16:17 UTC, MaiCaiIney requested changes
Faltan las validaciones de los campos obligatorios para el registro del usuario.

2023-07-07 17:58 UTC, Damian-Pereyra-dv commented
Validaciones Agregadas

2023-07-09 20:24 UTC, MaiCaiIney approved these changes

2023-07-09 20:24 UTC, merged