BBVAFSW3T3-28 - Endpoint para listar cuentas por usuario
alkemyTech/BBVA-FS-W3-Back-T3 pull request #14
Opened 2023-07-06 14:13 UTC by DiegoApro

Endpoint para listar cuentas por usuario

2023-07-07 15:08 UTC, MaiCaiIney requested changes
Falta la collection de Postman para probar el endpoint

2023-07-07 15:51 UTC, DiegoApro commented
Collection Postman agregada

2023-07-07 16:08 UTC, MaiCaiIney requested changes
El request de la collection está incompleto
![image](https://github.com/alkemyTech/BBVA-FS-W3-Back-T3/assets/18317105/7c479814-4bb8-42aa-abfb-37b7be68b09c)

2023-07-07 18:59 UTC, DiegoApro commented
Ahora si, no lo habia guardado sorry.

2023-07-12 12:06 UTC, MaiCaiIney requested changes

2023-07-12 12:06 UTC, MaiCaiIney commented on wallet/src/main/java/com/bbva/wallet/services/AccountService.java
`AccountService` es una interface, no puede implementar métodos. La implementación de `getUserAccounts` va en `AccountServiceImpl`

2023-07-12 14:04 UTC, DiegoApro commented on wallet/src/main/java/com/bbva/wallet/services/AccountService.java
Listo cambios arreglados

2023-07-12 14:27 UTC, MaiCaiIney requested changes
El servicio devuelve las cuentas eliminadas del usuario. Falta la anotación `@Where` en la entidad `Account` para que filtre solamente las cuentas activas.

2023-07-12 14:49 UTC, MaiCaiIney approved these changes

2023-07-12 14:50 UTC, merged