BBVAFSW3T3-25 | Endpoint de Autenticación
alkemyTech/BBVA-FS-W3-Back-T3 pull request #16
Opened 2023-07-06 18:42 UTC by neyen-ergas

Endpoint de Autenticación

2023-07-07 15:06 UTC, MaiCaiIney requested changes
El login devuelve error 403
![image](https://github.com/alkemyTech/BBVA-FS-W3-Back-T3/assets/18317105/65e4f53f-ecd1-42a1-a35c-6ed46e7cabdc)

2023-07-07 15:26 UTC, robyspr commented
Resolvimos lo del 403 mergeando la rama  BBVAFSW3T3-23-V2 - Endpoint de registro de usuarios con esta, ya que la necesitábamos para tener el **/auth/register**
Agregamos a la collection lo necesario para probarlo también

2023-07-10 12:40 UTC, robyspr commented
Ya arreglamos los conflictos y compila

2023-07-10 13:50 UTC, MaiCaiIney commented on wallet/src/main/java/com/bbva/wallet/controllers/AuthenticationController.java
> +    public ResponseEntity<User> LogIn (@Valid @RequestBody UserLogInDTO userDto){
El endpoint debe devolver el token generado, además de la información del usuario logueado.

2023-07-10 14:46 UTC, robyspr commented on wallet/src/main/java/com/bbva/wallet/controllers/AuthenticationController.java
> +    public ResponseEntity<User> LogIn (@Valid @RequestBody UserLogInDTO userDto){
Ahh la tarea no mencionaba lo del token, se lo agregamos igual?

2023-07-11 15:24 UTC, MaiCaiIney approved these changes

2023-07-11 15:25 UTC, merged