BBVAFSW3T3-29 - Devolver el token al usuario luego de registrarse
alkemyTech/BBVA-FS-W3-Back-T3 pull request #17
Opened 2023-07-07 16:35 UTC by Damian-Pereyra-dv

Devolver el token al usuario luego de registrarse y log

2023-07-07 18:23 UTC, robyspr commented
@Damian-Pereyra-dv hay que arreglar los conflictos del PR :p

2023-07-11 16:05 UTC, Damian-Pereyra-dv commented
resuelvo conflictos

2023-07-12 13:01 UTC, MaiCaiIney requested changes

2023-07-12 13:01 UTC, MaiCaiIney commented on wallet/src/main/java/com/bbva/wallet/controllers/AuthenticationController.java
> +        return ResponseEntity.ok(response);
`JwtAuthResponse` tiene un campo user que no se está completando, por lo que la información del usuario registrado no se está devolviendo. El endpoint de registro debe retornar la información del usuario creado y su token para autenticarse.

2023-07-12 14:32 UTC, Damian-Pereyra-dv commented on wallet/src/main/java/com/bbva/wallet/services/AuthenticationService.java
> +    private double transactionLimitArs;
son propertyValues que asignamos desde el aplication.properties. Los usamos en la creación de las cuentas para establecer los limites de transacciones. Aunque se indiquen que no están en uso se utilizan y funcionan debajo conde se crea la cuenta.

2023-07-13 15:07 UTC, merged